In [1]:
%matplotlib inline

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score

In [2]:
white_training_df1 = pd.read_csv('D:/Study/3rd Sem/ECEN 689/Challenge 4 - Wine Testing/Part 1/winequality-white-training.csv')
white_testing_df1 = pd.read_csv('D:/Study/3rd Sem/ECEN 689/Challenge 4 - Wine Testing/Part 1/winequality-white-testing.csv')

In [6]:
white_training_df = white_training_df1.drop(labels='Id', axis=1) 
white_testing_df = white_testing_df1.drop(labels='Id', axis=1)

In [3]:
red_training_df1 = pd.read_csv('D:/Study/3rd Sem/ECEN 689/Challenge 4 - Wine Testing/Part 3/winequality-red-training.csv')
red_testing_df1 = pd.read_csv('D:/Study/3rd Sem/ECEN 689/Challenge 4 - Wine Testing/Part 3/winequality-red-testing.csv')

In [7]:
red_training_df = red_training_df1.drop(labels='Id', axis=1) 
red_testing_df = red_testing_df1.drop(labels='Id', axis=1)

In [8]:
x_train = white_training_df.drop('quality', axis=1)

In [9]:
from sklearn.linear_model import LinearRegression

In [10]:
lm = LinearRegression()
lm

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [11]:
lm.fit(x_train,white_training_df.quality)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [13]:
x_test = red_testing_df

In [14]:
y_pred = lm.predict(x_test)

In [17]:
y_pred_df = pd.DataFrame(y_pred,columns=["quality"])

In [18]:
y_pred_df.insert(loc = 0,column = 'Id',value = red_training_df1.Id)

In [19]:
y_pred_df

      Id   quality
0      0  4.787937
1      1  4.730675
2      2  6.120424
3      3  3.962740
4      4  3.989580
5      5  4.433662
6      6  4.635170
7      7  4.918009
8      8  4.590618
9      9  4.438704
10    10  4.103070
11    11  6.373044
12    12  3.887714
13    13  4.638290
14    14  4.162629
15    15  5.455762
16    16  4.472219
17    17  4.236338
18    18  4.243351
19    19  4.740153
20    20  5.455762
21    21  4.282315
22    22  5.773001
23    23  6.145553
24    24  4.548226
25    25  3.460097
26    26  4.319948
27    27  4.058510
28    28  4.578779
29    29  5.236706
..   ...       ...
370  370  5.403930
371  371  5.574531
372  372  3.887714
373  373  4.135759
374  374  4.000060
375  375  4.790965
376  376  4.680779
377  377  4.271576
378  378  5.842044
379  379  5.905413
380  380  4.480958
381  381  5.002360
382  382  4.696790
383  383  5.134396
384  384  3.676195
385  385  4.344317
386  386  5.509389
387  387  5.446278
388  388  5.221756
389  389  5.410971
390  390  4.269979
391  391  5.191175
392  392  4.812258
393  393  5.097904
394  394  5.601933
395  395  5.726606
396  396  4.836729
397  397  5.386159
398  398  4.349680
399  399  4.444346

[400 rows x 2 columns]

In [20]:
y_pred_df.to_csv("D:/Study/3rd Sem/ECEN 689/Challenge 4 - Wine Testing/Part 3/" + "winequality-red-solution.csv",index=False)