# Challenge 1

## Reading Materials

### Required Reading
Due: September 6, 2018

 * Understanding Machine Learning from Theory to Algorithms, S. Shalev-Shwartz and S. Ben-David
   * **Chapter 1**: A gentle start
   * **Chapter 9**: Linear predictors
   

### [Kaggle Tutorials](https://www.kaggle.com/learn/overview)
Due: September 6, 2018

 * __Complete__ [Python course](https://www.kaggle.com/learn/python), if needed
 * __Complete__ [Pandas course](https://www.kaggle.com/learn/pandas), if needed


## Activity 1
Due: September 6, 2018

In Activity 1, you are tasked with estimating the mean and variance of a series of data sets, two parameters for every row.
Each student has their own file, and should work in place.
```python
student_identity = 'netid'
filename = '1challenge1activity_' + student_identity + '.csv'
```

### Deliverables
 1. Fill column ```Mean``` and ```Variance```.
 2. Commit your change on Git.

### Metric
 * Average $L_2$ norm between the true and estimated parameters.

In [1]:
import pandas as pd
import numpy as np

student_identity = 'shirishpandagare'
filenameToRead = '1challenge1activity_' + student_identity + '.csv'
filename = '1challenge1activity_' + student_identity + '.csv'
sample_df = pd.read_csv('1Files/' + filenameToRead)

list = []
for row in range(sample_df.shape[0]):
    array =  [sample_df['Sample 0'][row],sample_df['Sample 1'][row],
        sample_df['Sample 2'][row],sample_df['Sample 3'][row],
        sample_df['Sample 4'][row],sample_df['Sample 5'][row],
        sample_df['Sample 6'][row],sample_df['Sample 7'][row],
        sample_df['Sample 8'][row],sample_df['Sample 9'][row],
        sample_df['Sample 10'][row],sample_df['Sample 11'][row]]
    list.append([np.mean(array),np.var(array)])

for row in range(sample_df.shape[0]):
    sample_df.iloc[row, sample_df.columns.get_loc('Mean')] = list[row][0]
    sample_df.iloc[row, sample_df.columns.get_loc('Variance')] = list[row][1]

sample_df.head()

,Unnamed: 0,Mean,Variance,Sample 0,Sample 1,Sample 2,Sample 3,Sample 4,Sample 5,Sample 6,Sample 7,Sample 8,Sample 9,Sample 10,Sample 11
0,0,2.119433,1.119747,2.616189,2.830185,0.991320,1.562897,2.419671,2.343796,3.746485,2.227070,0.694528,2.087657,3.720070,0.193326
1,1,0.059990,0.727685,1.493008,0.703440,-0.386943,-0.617847,-1.733662,-0.616218,0.040254,-0.153087,0.902638,-0.241181,0.244613,1.084863
2,2,0.115223,1.023979,-0.458958,0.912629,-1.229525,0.208358,0.439420,-2.161751,1.296718,0.455579,0.217382,-0.283149,1.697835,0.288135
3,3,1.060927,0.996189,2.024959,0.174456,2.290035,0.628772,1.316776,0.245732,-0.572502,2.784124,0.105280,2.009781,1.236873,0.486842
4,4,-0.141460,0.464330,-0.702778,-0.354925,0.868471,1.209496,-0.452441,-0.319877,-0.204222,-0.427472,0.598256,-0.283565,-0.231402,-1.397059

In [2]:
sample_df.to_csv(filename, sep=',', encoding='utf-8')