# Challenge 1

## Reading Materials

### Required Reading
Due: September 6, 2018

 * Understanding Machine Learning from Theory to Algorithms, S. Shalev-Shwartz and S. Ben-David
   * **Chapter 1**: A gentle start
   * **Chapter 9**: Linear predictors
   

### [Kaggle Tutorials](https://www.kaggle.com/learn/overview)
Due: September 6, 2018

 * __Complete__ [Python course](https://www.kaggle.com/learn/python), if needed
 * __Complete__ [Pandas course](https://www.kaggle.com/learn/pandas), if needed


## Activity 1
Due: September 6, 2018

In Activity 1, you are tasked with estimating the mean and variance of a series of data sets, two parameters for every row.
Each student has their own file, and should work in place.
```python
student_identity = 'netid'
filename = '1challenge1activity_' + student_identity + '.csv'
```

### Deliverables
 1. Fill column ```Mean``` and ```Variance```.
 2. Commit your change on Git.

### Metric
 * Average $L_2$ norm between the true and estimated parameters.

In [1]:
import pandas as pd
import numpy as np

student_identity = 'devarshjhaveri'
filenameToRead = '1challenge1activity_' + student_identity + '.csv'
filename = '1challenge1activity_' + student_identity + '.csv'
sample_df = pd.read_csv('/Users/devarshjhaveri/Desktop/Courses/ECEN689-Fall2018/Challenges/1Files/' + filenameToRead)

sample_df.head(5)

,Unnamed: 0,Mean,Variance,Sample 0,Sample 1,Sample 2,Sample 3,Sample 4,Sample 5,Sample 6,Sample 7,Sample 8,Sample 9,Sample 10,Sample 11
0,0,NaN,NaN,-2.103177,-2.769136,-2.138943,-3.347936,-1.847351,-3.789634,-3.646108,-1.873697,-2.240381,-3.004370,-1.420302,-1.060125
1,1,NaN,NaN,-0.199399,-0.133722,0.068899,0.871480,0.558739,0.184605,0.400840,-0.691588,1.047927,0.689043,-0.233979,0.286878
2,2,NaN,NaN,0.276139,-1.928583,-1.089935,-0.874479,-1.104474,1.219641,2.185642,-1.011840,-0.324079,-1.001395,0.527388,-1.599697
3,3,NaN,NaN,1.671805,2.303514,1.608517,-1.667985,2.335358,1.034419,0.714737,1.021316,3.179472,0.353695,2.263129,2.200933
4,4,NaN,NaN,-0.974982,-0.442136,0.328997,0.390833,0.585141,-0.613627,-0.391136,0.376207,2.518862,-0.296154,-0.519340,0.371412

In [2]:
sample_df['Mean'] = np.mean(sample_df[sample_df.columns[3:15]], axis=1)
sample_df['Variance'] = np.var(sample_df[sample_df.columns[3:15]],ddof=1, axis=1)
sample_df.head(5)

,Unnamed: 0,Mean,Variance,Sample 0,Sample 1,Sample 2,Sample 3,Sample 4,Sample 5,Sample 6,Sample 7,Sample 8,Sample 9,Sample 10,Sample 11
0,0,-2.436763,0.762453,-2.103177,-2.769136,-2.138943,-3.347936,-1.847351,-3.789634,-3.646108,-1.873697,-2.240381,-3.004370,-1.420302,-1.060125
1,1,0.237477,0.258212,-0.199399,-0.133722,0.068899,0.871480,0.558739,0.184605,0.400840,-0.691588,1.047927,0.689043,-0.233979,0.286878
2,2,-0.393806,1.485508,0.276139,-1.928583,-1.089935,-0.874479,-1.104474,1.219641,2.185642,-1.011840,-0.324079,-1.001395,0.527388,-1.599697
3,3,1.418243,1.601048,1.671805,2.303514,1.608517,-1.667985,2.335358,1.034419,0.714737,1.021316,3.179472,0.353695,2.263129,2.200933
4,4,0.111173,0.828385,-0.974982,-0.442136,0.328997,0.390833,0.585141,-0.613627,-0.391136,0.376207,2.518862,-0.296154,-0.519340,0.371412

In [3]:
sample_df.to_csv('/Users/devarshjhaveri/Desktop/Courses/ECEN689-Fall2018/Challenges/1Files/' + filename)