In [0]:
from PIL import Image
import numpy as np
import scipy
from scipy import ndimage
import matplotlib.pyplot as plt
import re

In [0]:
import os
from glob import glob

In [4]:
# Load the Drive helper and mount
from google.colab import drive

# This will prompt for authorization.
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive

In [0]:
x=glob("/content/drive/My Drive/ECEN" + '/*.jpg')

In [6]:
np.asarray(x).shape

(1320,)

In [0]:
import pandas as pd
train = pd.read_csv('train.csv')
test= pd.read_csv('sample.csv')

In [0]:
train['Id']= train['Id'].astype('object')
test['Id']= test['Id'].astype('object')

In [0]:
filenames1= list(train['Id'])
filenames2= list(test['Id'])

In [0]:
filenames1

In [10]:
np.asarray(filenames1).shape

(792,)

In [11]:
filename=[]
train_array=[]
test_array=[]
for i in x:
  num = re.findall('\d+', i)
  filename.append(num)
  image = np.array(ndimage.imread(i, flatten=False))
  if int(num[0]) in filenames1:
    train_array.append(image)
  else:
    test_array.append(image)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: DeprecationWarning: `imread` is deprecated!
`imread` is deprecated in SciPy 1.0.0.
Use ``matplotlib.pyplot.imread`` instead.
  import sys

In [0]:
train_array

In [13]:
np.asanyarray(train_array).shape

(792, 300, 400, 3)

In [0]:
filename1=pd.DataFrame(filename, columns=['Id'], dtype='int')

In [0]:
filename1

In [15]:
np.asarray(test_array).shape

(528, 300, 400, 3)

In [16]:
np.asarray(test_array).shape

(528, 300, 400, 3)

In [0]:
test_array=np.asarray(test_array)
train_array=np.asarray(train_array)

In [0]:
test_array

In [0]:
test_x_flatten = test_array.reshape(test_array.shape[0], -1).T
train_x_flatten = train_array.reshape(train_array.shape[0], -1).T

In [88]:
train_x_flatten

array([[ 62, 105,  68, ...,  41, 114,  95],
       [ 74, 137, 102, ...,  59, 129, 111],
       [ 64, 124,  88, ...,  47, 126, 110],
       ...,
       [ 94, 103,  78, ...,  64, 128,  57],
       [111, 133, 108, ...,  77, 147,  52],
       [103, 125, 100, ...,  67, 143,  48]], dtype=uint8)

In [0]:
X_train = train_array / 255
X_test = test_array/ 255

In [35]:
X_test.dtype

dtype('float64')

In [20]:
filename1.shape

(1320, 1)

In [25]:
train.head()

         Id      DGCI
0  41367835 -0.320235
1  56194592 -0.322221
2  75713836 -0.312795
3   1169576 -0.312034
4  88155343 -0.318707

In [0]:
train_new= pd.merge(filename1,train, on='Id', how='left')

In [0]:
test_new= pd.merge(filename1,test, on='Id', how='left')

In [0]:
test_new.dropna(inplace=True)

In [0]:
test1 = test_new.reset_index(drop=True)

In [115]:
test1

           Id  DGCI
0    25715192   0.0
1    25947408   0.0
2    25785323   0.0
3    25701199   0.0
4    25987554   0.0
5    26488575   0.0
6    26238228   0.0
7    25988116   0.0
8    26597586   0.0
9    26643443   0.0
10   26739875   0.0
11   26876680   0.0
12   27356258   0.0
13   27372252   0.0
14   27258947   0.0
15   27194614   0.0
16   27028448   0.0
17   27760551   0.0
18   27844307   0.0
19   28021239   0.0
20   27841462   0.0
21   28100251   0.0
22   28785915   0.0
23   28311243   0.0
24   28493917   0.0
25   29481024   0.0
26   29218250   0.0
27   29556454   0.0
28   29782697   0.0
29   30010020   0.0
..        ...   ...
498  18900213   0.0
499  19116512   0.0
500  19705538   0.0
501  19282492   0.0
502  18964332   0.0
503  20270223   0.0
504  20176231   0.0
505  20154303   0.0
506  20615787   0.0
507  20770771   0.0
508  21040435   0.0
509  20766190   0.0
510  21195862   0.0
511  20690642   0.0
512  21541518   0.0
513  21689941   0.0
514  22154846   0.0
515  22214553   0.0
516  22392367   0.0
517  21212656   0.0
518  22815980   0.0
519  22464184   0.0
520  23536231   0.0
521  24194518   0.0
522  23220427   0.0
523  23814389   0.0
524  24232808   0.0
525  24925465   0.0
526  25394327   0.0
527  25386603   0.0

[528 rows x 2 columns]

In [0]:
train_new.dropna(inplace=True)

In [0]:
train_new

In [281]:
b=[]
for i in x:
  image=np.array(ndimage.imread(i, flatten=False))
  if image.shape != (300,400,3):
    print(i)
    b.append(i)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: DeprecationWarning: `imread` is deprecated!
`imread` is deprecated in SciPy 1.0.0.
Use ``matplotlib.pyplot.imread`` instead.
  This is separate from the ipykernel package so we can avoid doing imports until

In [282]:
b

[]

In [24]:
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasRegressor
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from keras.models import Sequential
from keras.layers import Dense, Activation, Dropout, Flatten, Conv2D, MaxPooling2D,MaxPool2D
from keras.optimizers import SGD, Adam
from keras.utils import to_categorical
from keras import optimizers
from sklearn.preprocessing import StandardScaler
import keras
from keras.layers import Dense, Dropout, Flatten, Activation, BatchNormalization, regularizers

Using TensorFlow backend.

In [0]:
def baseline_model3():
  model = Sequential()
  model.add(Conv2D(32, kernel_size=(3, 3),activation='relu',kernel_initializer='he_normal',input_shape=(300,400,3)))
  model.add(Conv2D(32, kernel_size=(3, 3),activation='relu',kernel_initializer='he_normal'))
  model.add(BatchNormalization())
  model.add(MaxPool2D((2, 2)))
  model.add(Dropout(0.20))
  model.add(Conv2D(64, (3, 3), activation='relu',padding='same',kernel_initializer='he_normal'))
  model.add(Conv2D(64, (3, 3), activation='relu',padding='same',kernel_initializer='he_normal'))
  model.add(BatchNormalization())
  model.add(MaxPool2D(pool_size=(2, 2)))
  model.add(Dropout(0.25))
  model.add(Conv2D(128, (3, 3), activation='relu',padding='same',kernel_initializer='he_normal'))
  model.add(BatchNormalization())
  model.add(Dropout(0.25))
  model.add(Flatten())
  model.add(Dense(128, activation='relu'))
  model.add(BatchNormalization())
  model.add(Dropout(0.25))
  model.add(Dense(1))
  model.compile(loss='mean_squared_error', optimizer='Adam')
  return model
#model.compile(loss=keras.losses.categorical_crossentropy,
 #             optimizer=keras.optimizers.RMSprop(),
  #            metrics=['accuracy'])

#learning_rate_reduction = ReduceLROnPlateau(monitor='val_acc', 
   #                                         patience=3, 
    #                                       factor=0.5, 
     #                                       min_lr=0.0001)

In [0]:
def baseline_model():
	# create model
  model = Sequential()
  model.add(Conv2D(32, (5,5), input_shape=(300,400,3), activation='relu'))
  model.add(Conv2D(32, (5,5), activation='relu'))
  model.add(MaxPooling2D(3,3))
  model.add(Conv2D(64, (5,5), activation='relu'))
  model.add(Conv2D(64, (5,5), activation='relu'))
  model.add(MaxPooling2D(3,3))
  model.add(Conv2D(128, (5,5), activation='relu'))
  model.add(MaxPooling2D(3,3))
  model.add(Flatten())
  model.add(Dense(units=256, activation='relu'))
  #model.add(Dropout(0.5))
  model.add(Dense(units=64, activation='relu'))
  model.add(Dense(units=32, activation='relu'))
  model.add(Dense(units=1))
  model.compile(loss='mean_squared_error', optimizer='Adam')
  return model

In [0]:
# evaluate model with standardized dataset
estimator = KerasRegressor(build_fn=baseline_model, epochs=10, batch_size=50, verbose=1)

In [0]:
y_train= np.array(train_new['DGCI'])

In [69]:
y_train.dtype

dtype('float64')

In [0]:
# kfold = KFold(n_splits=10)
# results = cross_val_score(estimator, X_train, y_train, cv=kfold)
# print("Larger: %.2f (%.2f) MSE" % (results.mean(), results.std()))

In [70]:
estimator.fit(X_train,y_train)

Epoch 1/10
792/792 [==============================] - 19s 24ms/step - loss: 0.2676
Epoch 2/10
792/792 [==============================] - 14s 17ms/step - loss: 0.0492
Epoch 3/10
792/792 [==============================] - 14s 17ms/step - loss: 0.0274
Epoch 4/10
792/792 [==============================] - 14s 17ms/step - loss: 0.0586
Epoch 5/10
792/792 [==============================] - 14s 17ms/step - loss: 0.0438
Epoch 6/10
792/792 [==============================] - 14s 17ms/step - loss: 0.0378
Epoch 7/10
792/792 [==============================] - 14s 17ms/step - loss: 0.0329
Epoch 8/10
792/792 [==============================] - 14s 17ms/step - loss: 0.0293
Epoch 9/10
792/792 [==============================] - 14s 17ms/step - loss: 0.0231
Epoch 10/10
792/792 [==============================] - 14s 17ms/step - loss: 0.0258

In [61]:
predictions = estimator.predict(X_train)
predictions

792/792 [==============================] - 6s 8ms/step

array([0.34114787, 0.34118304, 0.3411496 , 0.34114787, 0.34118888,
       0.34114787, 0.34117454, 0.34118408, 0.34116212, 0.3411499 ,
       0.34117234, 0.3411631 , 0.34114864, 0.34116685, 0.34114787,
       0.3411502 , 0.34114787, 0.34114787, 0.34115216, 0.34116048,
       0.34115934, 0.3411503 , 0.34114787, 0.34117758, 0.3411495 ,
       0.34114787, 0.34115276, 0.34114787, 0.34116286, 0.34116504,
       0.341162  , 0.3411514 , 0.341156  , 0.3411609 , 0.34116358,
       0.34116876, 0.3411885 , 0.34114903, 0.34115624, 0.3411502 ,
       0.3411636 , 0.3411523 , 0.34118187, 0.34116057, 0.34114787,
       0.34115168, 0.34114787, 0.34114787, 0.3411484 , 0.34115016,
       0.34117168, 0.3411585 , 0.34114948, 0.3411787 , 0.34114924,
       0.3411556 , 0.3411483 , 0.34115687, 0.34115472, 0.3411508 ,
       0.3411611 , 0.34115806, 0.34115705, 0.34115654, 0.34116971,
       0.34114787, 0.34115762, 0.3411764 , 0.34116122, 0.34117255,
       0.34115025, 0.34116137, 0.3411563 , 0.3411514 , 0.34114918,
       0.34114787, 0.3411901 , 0.34115067, 0.34114787, 0.34114787,
       0.3411719 , 0.34115696, 0.34117904, 0.34114787, 0.34115   ,
       0.34115207, 0.3411534 , 0.3411584 , 0.34114787, 0.34114787,
       0.34118482, 0.34114873, 0.34117892, 0.34117582, 0.34115136,
       0.34116912, 0.34115225, 0.34114823, 0.3411609 , 0.34115198,
       0.34116146, 0.34114787, 0.34114787, 0.34116557, 0.34116873,
       0.34114787, 0.34118003, 0.34117097, 0.3411747 , 0.34117055,
       0.34117356, 0.3411493 , 0.341162  , 0.34115303, 0.34114787,
       0.34116837, 0.34115267, 0.34115937, 0.34114787, 0.34115928,
       0.34117877, 0.34115034, 0.34116068, 0.34114787, 0.34116462,
       0.3411534 , 0.34117493, 0.34115618, 0.34114859, 0.34114787,
       0.34115452, 0.34115958, 0.3411508 , 0.34115192, 0.34117424,
       0.34114787, 0.34115383, 0.34117535, 0.3411565 , 0.34121397,
       0.34117445, 0.34114787, 0.34114787, 0.34121227, 0.3411513 ,
       0.341181  , 0.3411496 , 0.3411524 , 0.34114954, 0.3411534 ,
       0.34114787, 0.3411814 , 0.34115607, 0.34121624, 0.34114787,
       0.34114817, 0.34117094, 0.34117186, 0.34116513, 0.34114787,
       0.34115246, 0.3411893 , 0.34115493, 0.3411497 , 0.34114787,
       0.34114787, 0.34115985, 0.34114894, 0.34114847, 0.3411579 ,
       0.341187  , 0.34116417, 0.34121373, 0.3411489 , 0.34117678,
       0.34117678, 0.34116668, 0.3411564 , 0.3411629 , 0.34114787,
       0.3411482 , 0.3411503 , 0.34114787, 0.34121993, 0.34115604,
       0.34116608, 0.34115168, 0.34115195, 0.34116405, 0.34115452,
       0.34115294, 0.3411535 , 0.34115952, 0.34115082, 0.34122384,
       0.3411525 , 0.34114787, 0.34117225, 0.34114987, 0.34114787,
       0.34120685, 0.34116513, 0.34115824, 0.3411618 , 0.34114987,
       0.34115592, 0.34116736, 0.34115034, 0.34114787, 0.34114787,
       0.34116033, 0.34116277, 0.3411672 , 0.34114936, 0.34114787,
       0.34114787, 0.34115824, 0.3411506 , 0.34114864, 0.34118307,
       0.3411728 , 0.34116617, 0.34118634, 0.34114787, 0.34114853,
       0.34120616, 0.34115598, 0.34114888, 0.34114847, 0.34114787,
       0.34116393, 0.34117728, 0.34115005, 0.34115523, 0.34115133,
       0.3411501 , 0.34116903, 0.34115174, 0.34115475, 0.34115735,
       0.34114787, 0.34114894, 0.34114787, 0.34117854, 0.34115842,
       0.34114838, 0.3411777 , 0.34115484, 0.3411484 , 0.34116375,
       0.34114978, 0.34115854, 0.34115294, 0.34115735, 0.34116057,
       0.3411522 , 0.341148  , 0.34114894, 0.34114787, 0.3411504 ,
       0.34117815, 0.34115517, 0.3411506 , 0.34119055, 0.34115133,
       0.34117338, 0.3411684 , 0.34117553, 0.34114859, 0.3411549 ,
       0.3411685 , 0.3411506 , 0.3411749 , 0.3411524 , 0.34115365,
       0.34115857, 0.34114873, 0.34114942, 0.3411487 , 0.34114954,
       0.34116772, 0.34114996, 0.34114978, 0.3411566 , 0.34114787,
       0.34124333, 0.3411561 , 0.34114787, 0.3411793 , 0.34116545,
       0.34115928, 0.34115037, 0.3411688 , 0.3411512 , 0.341163  ,
       0.34114787, 0.34114787, 0.3411729 , 0.3411626 , 0.34116238,
       0.34114853, 0.34114787, 0.34115523, 0.34114805, 0.3411512 ,
       0.34115115, 0.34115127, 0.34115347, 0.34114924, 0.34115428,
       0.34114948, 0.34114787, 0.34114787, 0.341149  , 0.34114787,
       0.34114787, 0.3411519 , 0.34116262, 0.34116346, 0.34114787,
       0.34119028, 0.34115684, 0.34115577, 0.34118146, 0.34115934,
       0.3411625 , 0.34116474, 0.34115565, 0.3411481 , 0.34116244,
       0.3411691 , 0.3411657 , 0.34115714, 0.34115154, 0.34114787,
       0.341164  , 0.34116954, 0.34117925, 0.34116125, 0.34115043,
       0.34115297, 0.34116146, 0.34115103, 0.3411634 , 0.34114787,
       0.3411516 , 0.34119153, 0.34114942, 0.34116212, 0.3411521 ,
       0.34114856, 0.34115207, 0.34115988, 0.3411497 , 0.34117684,
       0.34120768, 0.34114823, 0.3411678 , 0.34114882, 0.3411687 ,
       0.3411706 , 0.34114787, 0.3411486 , 0.34115142, 0.34114787,
       0.341155  , 0.34117204, 0.34118834, 0.34114787, 0.34114787,
       0.34116092, 0.34116557, 0.34117836, 0.34114966, 0.3411493 ,
       0.34117046, 0.3411518 , 0.34116057, 0.34118232, 0.3411632 ,
       0.34117144, 0.34114787, 0.34115744, 0.34114975, 0.34115463,
       0.34117156, 0.34115362, 0.3411562 , 0.34114787, 0.34115675,
       0.34115127, 0.34114942, 0.34115073, 0.3411566 , 0.34116018,
       0.34115407, 0.34116134, 0.34116167, 0.34115165, 0.34118512,
       0.34114972, 0.3411525 , 0.341173  , 0.34114787, 0.34114793,
       0.34115288, 0.34116545, 0.34114844, 0.34115243, 0.3411489 ,
       0.34115303, 0.34115955, 0.34114826, 0.3411639 , 0.34115484,
       0.3411608 , 0.34114972, 0.34118912, 0.34116215, 0.3411757 ,
       0.34114787, 0.3411824 , 0.34119263, 0.34115887, 0.34114963,
       0.34116864, 0.3411574 , 0.34115347, 0.34115443, 0.34116632,
       0.34116477, 0.34115526, 0.34114787, 0.34115225, 0.3411713 ,
       0.34115425, 0.34114787, 0.3411507 , 0.3411508 , 0.34115687,
       0.3411494 , 0.34114787, 0.3411685 , 0.34114805, 0.34115645,
       0.34119105, 0.34118095, 0.34116903, 0.3411705 , 0.3411817 ,
       0.34114787, 0.34115067, 0.3411533 , 0.3411614 , 0.34115162,
       0.34114787, 0.3411532 , 0.34114808, 0.3411531 , 0.3411679 ,
       0.34114873, 0.34116644, 0.3411496 , 0.34114814, 0.34114963,
       0.34114888, 0.34115067, 0.34115642, 0.34115145, 0.34118807,
       0.34116384, 0.34114787, 0.34117475, 0.34119093, 0.34116623,
       0.34114787, 0.34114787, 0.3411545 , 0.34114787, 0.34116906,
       0.34117082, 0.34115118, 0.34114978, 0.34118018, 0.34114787,
       0.34117225, 0.34114787, 0.34115088, 0.341148  , 0.34116778,
       0.3411651 , 0.34115225, 0.34114787, 0.34115216, 0.34115687,
       0.34114787, 0.34115273, 0.34116817, 0.34114787, 0.3411804 ,
       0.3411563 , 0.34115782, 0.3411536 , 0.34115446, 0.34119147,
       0.34114787, 0.34114787, 0.341148  , 0.34116024, 0.34115884,
       0.3411523 , 0.34114787, 0.3411558 , 0.34115976, 0.34115666,
       0.34117776, 0.34114853, 0.34116518, 0.34115136, 0.3411603 ,
       0.34116143, 0.3411506 , 0.34114787, 0.34116352, 0.34114975,
       0.34115908, 0.3411492 , 0.34114787, 0.34114787, 0.34116313,
       0.3411544 , 0.34114912, 0.3411576 , 0.34114906, 0.34122425,
       0.34115043, 0.34115693, 0.34114787, 0.34114787, 0.3411555 ,
       0.3411527 , 0.3411486 , 0.34115955, 0.34116852, 0.34115008,
       0.3411587 , 0.3411563 , 0.34118366, 0.3411632 , 0.34115052,
       0.34115872, 0.3411538 , 0.34114787, 0.34115207, 0.34115553,
       0.34117427, 0.3411538 , 0.34115732, 0.3411583 , 0.34115106,
       0.34116426, 0.34116802, 0.34114787, 0.34114897, 0.3411595 ,
       0.34115195, 0.34114787, 0.34116113, 0.34115642, 0.3411609 ,
       0.3411687 , 0.34114787, 0.34115213, 0.34114787, 0.3411525 ,
       0.34114787, 0.3411596 , 0.3411615 , 0.34116942, 0.34115204,
       0.3411694 , 0.34118333, 0.3411594 , 0.34114787, 0.34115404,
       0.34119904, 0.3411512 , 0.34114787, 0.34114963, 0.34115684,
       0.3411543 , 0.34116665, 0.34114978, 0.34114787, 0.34114787,
       0.34114787, 0.34114867, 0.34114787, 0.34116653, 0.34114787,
       0.3411566 , 0.34114787, 0.34115025, 0.34116614, 0.34114787,
       0.34115675, 0.34118128, 0.3411517 , 0.34117603, 0.3411769 ,
       0.34114787, 0.34116757, 0.34117073, 0.34116837, 0.34115428,
       0.341163  , 0.34117723, 0.34114787, 0.34120217, 0.34116256,
       0.34115925, 0.34116688, 0.34115332, 0.34116304, 0.34115282,
       0.3411493 , 0.3411669 , 0.3411642 , 0.34114787, 0.34115326,
       0.34116375, 0.34114787, 0.3411532 , 0.34115067, 0.34115234,
       0.34115165, 0.3411689 , 0.3411488 , 0.34115043, 0.34117752,
       0.3411651 , 0.34114787, 0.34114787, 0.34118667, 0.3411505 ,
       0.3411584 , 0.3411592 , 0.34115857, 0.34115583, 0.341209  ,
       0.34115812, 0.3411481 , 0.34114787, 0.34114847, 0.341162  ,
       0.3411543 , 0.34115443, 0.34115967, 0.34115043, 0.34115627,
       0.34114805, 0.3411585 , 0.34116295, 0.34115428, 0.34115636,
       0.3411499 , 0.34116444, 0.34116337, 0.34114996, 0.34116048,
       0.34118927, 0.34115794, 0.34114787, 0.34116745, 0.34115395,
       0.34114864, 0.34115756, 0.34116763, 0.3411525 , 0.34115723,
       0.34116173, 0.34115472, 0.34116432, 0.3412516 , 0.3411524 ,
       0.34115216, 0.3411568 , 0.34116316, 0.34116602, 0.34115517,
       0.34114787, 0.3412416 , 0.3411636 , 0.34114787, 0.3411637 ,
       0.34115908, 0.34114853, 0.3411629 , 0.3411496 , 0.3411717 ,
       0.34115365, 0.34115985, 0.34115845, 0.34115222, 0.34114787,
       0.34115294, 0.34114787, 0.3411759 , 0.3411515 , 0.3411598 ,
       0.3411634 , 0.3411543 , 0.34114787, 0.34115216, 0.34114787,
       0.34115076, 0.3411483 , 0.34114787, 0.34118617, 0.3411563 ,
       0.34117013, 0.34114787, 0.34115675, 0.34118342, 0.34115878,
       0.34115526, 0.3411521 , 0.3412019 , 0.3411481 , 0.34116703,
       0.34116083, 0.3411563 , 0.34114787, 0.34114912, 0.34114912,
       0.34114787, 0.34116775, 0.3411589 , 0.3411538 , 0.3411536 ,
       0.34117684, 0.34116784, 0.34117395, 0.34115613, 0.3411596 ,
       0.3411529 , 0.3411796 , 0.3411503 , 0.34116235, 0.34114787,
       0.3411788 , 0.34116557, 0.34115297, 0.34114787, 0.34117725,
       0.34115338, 0.34114894, 0.3411578 , 0.34114787, 0.34115985,
       0.3411509 , 0.3411615 , 0.34118718, 0.34116805, 0.34114787,
       0.34114787, 0.34116575, 0.34116593, 0.34114787, 0.34115836,
       0.34114906, 0.34115592, 0.34115952, 0.3411728 , 0.34116724,
       0.34115845, 0.3411562 , 0.34115192, 0.34119636, 0.34116426,
       0.34115192, 0.34116033, 0.3411505 , 0.34114787, 0.34115532,
       0.34114787, 0.34115416, 0.3411519 , 0.34116066, 0.34115583,
       0.3411558 , 0.34115532], dtype=float32)

In [62]:
from sklearn.metrics import mean_squared_error
np.sqrt(mean_squared_error(y_train,predictions))

0.2511760409166988

In [71]:
z = estimator.predict(X_test)

528/528 [==============================] - 4s 8ms/step

In [72]:
z

array([0.49466032, 0.5540724 , 0.48023558, 0.5533296 , 0.49424577,
       0.5002624 , 0.54371077, 0.5328386 , 0.5572515 , 0.5037038 ,
       0.55134284, 0.49458176, 0.537707  , 0.53598344, 0.56349534,
       0.5607085 , 0.5254029 , 0.5546826 , 0.55592626, 0.5504131 ,
       0.4927689 , 0.5208287 , 0.53923076, 0.5212834 , 0.5390753 ,
       0.5256864 , 0.4988301 , 0.53953385, 0.49924573, 0.55634606,
       0.4937418 , 0.5221709 , 0.5252414 , 0.5210254 , 0.5351772 ,
       0.5329964 , 0.53509825, 0.57101065, 0.48846304, 0.5716255 ,
       0.5518588 , 0.5536411 , 0.49523622, 0.54644316, 0.5532764 ,
       0.48501807, 0.55285746, 0.54483026, 0.5475634 , 0.55186653,
       0.5054937 , 0.5554787 , 0.49845508, 0.5453099 , 0.50925004,
       0.5573886 , 0.5194836 , 0.48766667, 0.5504889 , 0.5421879 ,
       0.54698575, 0.5440837 , 0.55616885, 0.46566653, 0.54326344,
       0.552071  , 0.5521502 , 0.5538705 , 0.5158499 , 0.56125605,
       0.48691955, 0.531254  , 0.5046731 , 0.5527289 , 0.49707177,
       0.54886854, 0.5189028 , 0.56556827, 0.55216354, 0.5751606 ,
       0.5035678 , 0.49973574, 0.55629385, 0.4953722 , 0.5562414 ,
       0.53203154, 0.5089955 , 0.4890676 , 0.52319884, 0.5502821 ,
       0.507083  , 0.5363526 , 0.580745  , 0.5142039 , 0.55200857,
       0.5651037 , 0.549806  , 0.5157298 , 0.49021724, 0.49775398,
       0.521299  , 0.55283463, 0.49473307, 0.48237395, 0.5260356 ,
       0.49179292, 0.53094614, 0.5413711 , 0.53835434, 0.5670485 ,
       0.5686889 , 0.54250896, 0.49877635, 0.48918018, 0.53424007,
       0.5234423 , 0.550101  , 0.5293828 , 0.49635783, 0.54726857,
       0.5529966 , 0.49540618, 0.4978257 , 0.5371167 , 0.501626  ,
       0.5553587 , 0.5514004 , 0.5547666 , 0.54196686, 0.558075  ,
       0.5361046 , 0.52239853, 0.5098221 , 0.5410982 , 0.55568093,
       0.5353821 , 0.54775286, 0.5391973 , 0.55462134, 0.49132124,
       0.5187704 , 0.4934794 , 0.53676724, 0.5460996 , 0.48943108,
       0.55308646, 0.5481345 , 0.5447396 , 0.54595304, 0.5417548 ,
       0.5679302 , 0.55347335, 0.4973587 , 0.5277131 , 0.5378909 ,
       0.55242014, 0.51919514, 0.5221596 , 0.54385865, 0.4936087 ,
       0.56407285, 0.5144576 , 0.5255726 , 0.5438475 , 0.49543884,
       0.53241706, 0.5175595 , 0.5614954 , 0.49677673, 0.551986  ,
       0.55597186, 0.53933674, 0.5504456 , 0.54758054, 0.552981  ,
       0.5398708 , 0.5320205 , 0.5534469 , 0.49614403, 0.56576204,
       0.55383223, 0.55544996, 0.56723547, 0.5663958 , 0.54065406,
       0.5223454 , 0.5525129 , 0.5491296 , 0.55538714, 0.5457842 ,
       0.4878731 , 0.5582548 , 0.55727464, 0.5404094 , 0.53249115,
       0.49645936, 0.5573568 , 0.5514112 , 0.5580367 , 0.5019707 ,
       0.54302734, 0.51883715, 0.5407897 , 0.53819335, 0.5251256 ,
       0.47858453, 0.5029852 , 0.5507907 , 0.55890346, 0.4970807 ,
       0.5525307 , 0.5063248 , 0.5038885 , 0.553122  , 0.54490966,
       0.53577244, 0.5279707 , 0.52579623, 0.5343598 , 0.5574318 ,
       0.49058276, 0.54507786, 0.5446192 , 0.49560943, 0.49412918,
       0.5567518 , 0.5557066 , 0.5527143 , 0.55229384, 0.5740625 ,
       0.5098949 , 0.4925843 , 0.49830022, 0.54294986, 0.53675663,
       0.5015879 , 0.5017288 , 0.5143362 , 0.5857588 , 0.57656187,
       0.5028786 , 0.5574246 , 0.5511289 , 0.5436388 , 0.48943207,
       0.5251482 , 0.55182827, 0.4894811 , 0.5553745 , 0.5133794 ,
       0.5449816 , 0.4905178 , 0.5497221 , 0.5378803 , 0.5489494 ,
       0.5249046 , 0.5156933 , 0.55364394, 0.5634991 , 0.4992372 ,
       0.52127105, 0.5445532 , 0.56274295, 0.48809862, 0.5285183 ,
       0.5612497 , 0.5154096 , 0.54302967, 0.51300335, 0.53595805,
       0.55107737, 0.54542   , 0.50553584, 0.5522905 , 0.5447613 ,
       0.5285944 , 0.5566526 , 0.5296622 , 0.55337346, 0.54399467,
       0.49072522, 0.48245725, 0.49953625, 0.4936655 , 0.49214774,
       0.53750944, 0.51348346, 0.57175285, 0.5420143 , 0.55014175,
       0.51344   , 0.5223094 , 0.5003138 , 0.5483935 , 0.5475307 ,
       0.5005989 , 0.49441576, 0.5218911 , 0.5403498 , 0.49434513,
       0.56686   , 0.53027475, 0.5543278 , 0.54025954, 0.48939663,
       0.54214823, 0.5384008 , 0.53596246, 0.54112136, 0.5454574 ,
       0.53561395, 0.55543536, 0.4937905 , 0.5566299 , 0.4983923 ,
       0.547012  , 0.5496215 , 0.549623  , 0.5355053 , 0.4953661 ,
       0.5546374 , 0.5573411 , 0.4995682 , 0.5367386 , 0.500214  ,
       0.551922  , 0.53701967, 0.5420627 , 0.54047436, 0.50638527,
       0.5495848 , 0.49611413, 0.5722875 , 0.5230238 , 0.49677074,
       0.55009705, 0.50221694, 0.55702734, 0.5041763 , 0.5051369 ,
       0.51609325, 0.56906223, 0.49636465, 0.55159444, 0.54012316,
       0.57212335, 0.5018149 , 0.54971766, 0.5257667 , 0.5485211 ,
       0.5410753 , 0.57800555, 0.48856065, 0.56623167, 0.48488328,
       0.49313542, 0.5462092 , 0.53832406, 0.5343572 , 0.5584099 ,
       0.5641098 , 0.48867527, 0.50257033, 0.54268426, 0.51925886,
       0.54700893, 0.54571426, 0.5031025 , 0.5369538 , 0.5700904 ,
       0.5356534 , 0.5550895 , 0.558282  , 0.5013444 , 0.54236376,
       0.5517365 , 0.5706974 , 0.54116064, 0.49975547, 0.511293  ,
       0.55054295, 0.5485481 , 0.49823883, 0.5484324 , 0.5011214 ,
       0.55848587, 0.5793415 , 0.49819955, 0.5093023 , 0.5589415 ,
       0.53560054, 0.55713516, 0.4917584 , 0.46324727, 0.4819919 ,
       0.5137693 , 0.47781807, 0.5550164 , 0.53812724, 0.54718536,
       0.49565932, 0.48087522, 0.48855832, 0.52851987, 0.5294578 ,
       0.5025435 , 0.5499026 , 0.48350814, 0.53898984, 0.55710405,
       0.54736495, 0.49235398, 0.5524461 , 0.55374664, 0.5555537 ,
       0.49992362, 0.5699801 , 0.4933772 , 0.5545077 , 0.5412848 ,
       0.5326387 , 0.50006944, 0.53416294, 0.5696721 , 0.48776707,
       0.54816586, 0.5353273 , 0.56674004, 0.5213459 , 0.550401  ,
       0.54186255, 0.5440693 , 0.49493855, 0.5416556 , 0.54967314,
       0.48543784, 0.49171922, 0.499787  , 0.51670176, 0.5493887 ,
       0.5418175 , 0.49002182, 0.5616885 , 0.49853417, 0.49820778,
       0.5767983 , 0.51387197, 0.5278851 , 0.4883528 , 0.5399867 ,
       0.5520323 , 0.5486821 , 0.5474635 , 0.55899155, 0.50557274,
       0.55101043, 0.48483685, 0.5411928 , 0.565871  , 0.54892415,
       0.5454849 , 0.5680681 , 0.5507703 , 0.5196149 , 0.559662  ,
       0.50271606, 0.55173653, 0.54556346, 0.5347437 , 0.53948855,
       0.5602551 , 0.50710547, 0.5490812 , 0.5490651 , 0.49098933,
       0.54293364, 0.5155741 , 0.5506105 , 0.5213645 , 0.540791  ,
       0.49150804, 0.5480142 , 0.5223327 , 0.5015281 , 0.5376196 ,
       0.5296304 , 0.55507094, 0.4858347 , 0.5431502 , 0.5468128 ,
       0.5435475 , 0.5456287 , 0.4893784 , 0.54560477, 0.5161558 ,
       0.544736  , 0.5477296 , 0.5239125 , 0.55291903, 0.5400002 ,
       0.48914883, 0.55292517, 0.49308655, 0.4991528 , 0.4917731 ,
       0.5342095 , 0.5692927 , 0.549322  , 0.5374888 , 0.5473584 ,
       0.5529016 , 0.4915256 , 0.5710318 , 0.49304652, 0.55200386,
       0.49391693, 0.5447607 , 0.48014304, 0.55033475, 0.5651359 ,
       0.5218579 , 0.54083407, 0.5595099 , 0.52717435, 0.4982594 ,
       0.55160725, 0.5598383 , 0.56987584], dtype=float32)

In [0]:
d = {'DGCI':pd.Series(z)}

In [0]:
s = pd.DataFrame(d,index=None)

In [117]:
s

         DGCI
0    0.494660
1    0.554072
2    0.480236
3    0.553330
4    0.494246
5    0.500262
6    0.543711
7    0.532839
8    0.557252
9    0.503704
10   0.551343
11   0.494582
12   0.537707
13   0.535983
14   0.563495
15   0.560709
16   0.525403
17   0.554683
18   0.555926
19   0.550413
20   0.492769
21   0.520829
22   0.539231
23   0.521283
24   0.539075
25   0.525686
26   0.498830
27   0.539534
28   0.499246
29   0.556346
..        ...
498  0.552919
499  0.540000
500  0.489149
501  0.552925
502  0.493087
503  0.499153
504  0.491773
505  0.534209
506  0.569293
507  0.549322
508  0.537489
509  0.547358
510  0.552902
511  0.491526
512  0.571032
513  0.493047
514  0.552004
515  0.493917
516  0.544761
517  0.480143
518  0.550335
519  0.565136
520  0.521858
521  0.540834
522  0.559510
523  0.527174
524  0.498259
525  0.551607
526  0.559838
527  0.569876

[528 rows x 1 columns]

In [0]:
test1['DGCI'] = s

In [119]:
test1

           Id      DGCI
0    25715192  0.494660
1    25947408  0.554072
2    25785323  0.480236
3    25701199  0.553330
4    25987554  0.494246
5    26488575  0.500262
6    26238228  0.543711
7    25988116  0.532839
8    26597586  0.557252
9    26643443  0.503704
10   26739875  0.551343
11   26876680  0.494582
12   27356258  0.537707
13   27372252  0.535983
14   27258947  0.563495
15   27194614  0.560709
16   27028448  0.525403
17   27760551  0.554683
18   27844307  0.555926
19   28021239  0.550413
20   27841462  0.492769
21   28100251  0.520829
22   28785915  0.539231
23   28311243  0.521283
24   28493917  0.539075
25   29481024  0.525686
26   29218250  0.498830
27   29556454  0.539534
28   29782697  0.499246
29   30010020  0.556346
..        ...       ...
498  18900213  0.552919
499  19116512  0.540000
500  19705538  0.489149
501  19282492  0.552925
502  18964332  0.493087
503  20270223  0.499153
504  20176231  0.491773
505  20154303  0.534209
506  20615787  0.569293
507  20770771  0.549322
508  21040435  0.537489
509  20766190  0.547358
510  21195862  0.552902
511  20690642  0.491526
512  21541518  0.571032
513  21689941  0.493047
514  22154846  0.552004
515  22214553  0.493917
516  22392367  0.544761
517  21212656  0.480143
518  22815980  0.550335
519  22464184  0.565136
520  23536231  0.521858
521  24194518  0.540834
522  23220427  0.559510
523  23814389  0.527174
524  24232808  0.498259
525  24925465  0.551607
526  25394327  0.559838
527  25386603  0.569876

[528 rows x 2 columns]

In [0]:
test_final= pd.merge(test,test1, on='Id', how='left')

In [125]:
test_final

           Id  DGCI_x    DGCI_y
0    79783930       0  0.513483
1    40239934       0  0.514204
2    50410534       0  0.518770
3    47165338       0  0.509822
4    16455157       0  0.529630
5    90938592       0  0.505137
6     1317745       0  0.538990
7    59791582       0  0.540654
8    14525631       0  0.515574
9    88602343       0  0.536739
10   23536231       0  0.521858
11   18553789       0  0.523912
12   81273029       0  0.513440
13   41102841       0  0.521299
14   67468796       0  0.535772
15   48298815       0  0.535382
16   93229470       0  0.493135
17   25785323       0  0.480236
18   30895645       0  0.525241
19   39503717       0  0.508995
20   91124259       0  0.516093
21   76528041       0  0.528518
22   73863630       0  0.513379
23   53397170       0  0.519195
24   64390024       0  0.502985
25    5495309       0  0.499787
26   96127913       0  0.501344
27   29592550       0  0.522171
28   53433017       0  0.522160
29   34588615       0  0.487667
..        ...     ...       ...
498  63924227       0  0.501971
499  83306614       0  0.494416
500  52848860       0  0.497359
501  99303349       0  0.498200
502  21212656       0  0.480143
503  37807073       0  0.497072
504  55406826       0  0.495439
505    722409       0  0.495659
506  75855645       0  0.499237
507  90625918       0  0.496771
508  45254131       0  0.496358
509  41969652       0  0.491793
510  57602072       0  0.496144
511   4960703       0  0.494939
512  68239016       0  0.490583
513   1429593       0  0.483508
514   3771586       0  0.487767
515  16729575       0  0.485835
516  79745295       0  0.482457
517  20270223       0  0.499153
518   1698550       0  0.492354
519  16034595       0  0.491508
520  25987554       0  0.494246
521  74134655       0  0.490518
522   5508544       0  0.491719
523  64510039       0  0.478585
524  73548399       0  0.489481
525   7058044       0  0.488353
526  43963238       0  0.489180
527  94012606       0  0.488675

[528 rows x 3 columns]

In [0]:
test2 = test_final[['Id','DGCI_y']]

In [0]:
test2.columns = ['Id','DGCI']

In [131]:
test2

           Id      DGCI
0    79783930  0.513483
1    40239934  0.514204
2    50410534  0.518770
3    47165338  0.509822
4    16455157  0.529630
5    90938592  0.505137
6     1317745  0.538990
7    59791582  0.540654
8    14525631  0.515574
9    88602343  0.536739
10   23536231  0.521858
11   18553789  0.523912
12   81273029  0.513440
13   41102841  0.521299
14   67468796  0.535772
15   48298815  0.535382
16   93229470  0.493135
17   25785323  0.480236
18   30895645  0.525241
19   39503717  0.508995
20   91124259  0.516093
21   76528041  0.528518
22   73863630  0.513379
23   53397170  0.519195
24   64390024  0.502985
25    5495309  0.499787
26   96127913  0.501344
27   29592550  0.522171
28   53433017  0.522160
29   34588615  0.487667
..        ...       ...
498  63924227  0.501971
499  83306614  0.494416
500  52848860  0.497359
501  99303349  0.498200
502  21212656  0.480143
503  37807073  0.497072
504  55406826  0.495439
505    722409  0.495659
506  75855645  0.499237
507  90625918  0.496771
508  45254131  0.496358
509  41969652  0.491793
510  57602072  0.496144
511   4960703  0.494939
512  68239016  0.490583
513   1429593  0.483508
514   3771586  0.487767
515  16729575  0.485835
516  79745295  0.482457
517  20270223  0.499153
518   1698550  0.492354
519  16034595  0.491508
520  25987554  0.494246
521  74134655  0.490518
522   5508544  0.491719
523  64510039  0.478585
524  73548399  0.489481
525   7058044  0.488353
526  43963238  0.489180
527  94012606  0.488675

[528 rows x 2 columns]

In [0]:
test2. to_csv('test2.csv',index=False)
from google.colab import files
files.download('test2.csv')